---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Exclude patterns - files that should not be analyzed
exclude_paths:
  # DevContainer internal docs and generated files
  - '.devcontainer/docs/**'
  - '.devcontainer/mcp.json'

  # Standard exclusions
  - 'node_modules/**'
  - 'vendor/**'
  - 'dist/**'
  - 'build/**'
  - '*.min.js'
  - '*.min.css'

# Engines configuration
engines:
  trivy:
    exclude_paths:
      - '.devcontainer/mcp.json'

  # Exclude test files from Lizard complexity analysis
  # Test functions are inherently longer due to table-driven patterns
  lizard:
    exclude_paths:
      - '**/*_test.go'
      - '**/testdata/**'

  # Exclude CLAUDE.md files from markdownlint
  # These are internal AI context files, not public documentation
  markdownlint:
    exclude_paths:
      - '**/CLAUDE.md'

  # Exclude testdata from Semgrep security checks
  # Testdata intentionally contains non-production patterns
  semgrep:
    exclude_paths:
      - '**/testdata/**'
