version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.25"

# Configuration minimale : uniquement KTN-Linter via le wrapper
# Aucun linter golangci-lint activé
linters:
  enable: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
