# Configuration KTN Linter
version: "1.0"

# Règles à ignorer dans les fichiers de test
test-files:
  patterns:
    - "**/*_test.go"
    - "**/*_unit_test.go"
    - "**/testdata/**/*.go"

  # Règles désactivées pour les tests
  disabled-rules:
    - KTN-FUNC-001  # Noms avec underscores OK pour tests (TestName_Scenario)
    - KTN-FUNC-002  # Godoc optionnel pour fonctions de test
    - KTN-FUNC-003  # Section Params: optionnelle pour tests
    - KTN-FUNC-004  # Section Returns: optionnelle pour tests
    - KTN-FUNC-008  # Return comments optionnels pour tests
    - KTN-FUNC-009  # Profondeur imbrication OK pour tests complexes
    - KTN-VAR-001   # Noms variables tests peuvent avoir underscores
    - KTN-VAR-003   # Commentaires variables optionnels pour tests
    - KTN-VAR-004   # Commentaires variables optionnels pour tests
    - KTN-RANGE-003 # Capture range vars OK si copie locale présente

# Règles globales
global:
  # Ignorer les fichiers générés
  exclude-patterns:
    - "**/testdata/**/*.go"
    - "**/.git/**"
    - "**/vendor/**"
