package utils_test

import (
	"go/ast"
	"go/token"
	"testing"

	"github.com/kodflow/ktn-linter/pkg/analyzer/utils"
	"golang.org/x/tools/go/analysis"
)

func TestIsTestFile(t *testing.T) {
	tests := []struct {
		name     string
		filename string
		want     bool
	}{
		{
			name:     "regular go file",
			filename: "main.go",
			want:     false,
		},
		{
			name:     "test file",
			filename: "main_test.go",
			want:     true,
		},
		{
			name:     "external test file",
			filename: "main_external_test.go",
			want:     true,
		},
		{
			name:     "internal test file",
			filename: "main_internal_test.go",
			want:     true,
		},
		{
			name:     "file with test in name",
			filename: "test_utils.go",
			want:     false,
		},
	}

	for _, tt := range tests {
		tt := tt // Capture range variable
		t.Run(tt.name, func(t *testing.T) {
			got := utils.IsTestFile(tt.filename)
			if got != tt.want {
				t.Errorf("IsTestFile(%q) = %v, want %v", tt.filename, got, tt.want)
			}
		})
	}
}

func TestIsGeneratedFile(t *testing.T) {
	tests := []struct {
		name string
		file *ast.File
		want bool
	}{
		{
			name: "regular file without comments",
			file: &ast.File{},
			want: false,
		},
		{
			name: "file with Code generated comment",
			file: &ast.File{
				Comments: []*ast.CommentGroup{
					{
						List: []*ast.Comment{
							{Text: "// Code generated by tool. DO NOT EDIT."},
						},
					},
				},
			},
			want: true,
		},
		{
			name: "file with DO NOT EDIT comment",
			file: &ast.File{
				Comments: []*ast.CommentGroup{
					{
						List: []*ast.Comment{
							{Text: "// DO NOT EDIT"},
						},
					},
				},
			},
			want: true,
		},
		{
			name: "file with unrelated comments",
			file: &ast.File{
				Comments: []*ast.CommentGroup{
					{
						List: []*ast.Comment{
							{Text: "// This is a normal comment"},
						},
					},
				},
			},
			want: false,
		},
	}

	for _, tt := range tests {
		tt := tt // Capture range variable
		t.Run(tt.name, func(t *testing.T) {
			got := utils.IsGeneratedFile(tt.file)
			if got != tt.want {
				t.Errorf("IsGeneratedFile() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestShouldSkipFile(t *testing.T) {
	fset := token.NewFileSet()

	tests := []struct {
		name     string
		filename string
		file     *ast.File
		want     bool
	}{
		{
			name:     "regular go file",
			filename: "main.go",
			file:     &ast.File{},
			want:     false,
		},
		{
			name:     "test file",
			filename: "main_test.go",
			file:     &ast.File{},
			want:     true,
		},
		{
			name:     "generated file",
			filename: "generated.go",
			file: &ast.File{
				Comments: []*ast.CommentGroup{
					{List: []*ast.Comment{{Text: "// Code generated"}}},
				},
			},
			want: true,
		},
	}

	for _, tt := range tests {
		tt := tt // Capture range variable
		t.Run(tt.name, func(t *testing.T) {
			f := fset.AddFile(tt.filename, -1, 100)
			tt.file.Package = f.Pos(0)
			pass := &analysis.Pass{
				Fset: fset,
			}
			got := utils.ShouldSkipFile(pass, tt.file)
			if got != tt.want {
				t.Errorf("ShouldSkipFile() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestShouldSkipTestFile(t *testing.T) {
	fset := token.NewFileSet()

	tests := []struct {
		name     string
		filename string
		want     bool
	}{
		{
			name:     "regular go file",
			filename: "main.go",
			want:     false,
		},
		{
			name:     "test file",
			filename: "main_test.go",
			want:     true,
		},
	}

	for _, tt := range tests {
		tt := tt // Capture range variable
		t.Run(tt.name, func(t *testing.T) {
			f := fset.AddFile(tt.filename, -1, 100)
			file := &ast.File{Package: f.Pos(0)}
			pass := &analysis.Pass{
				Fset: fset,
			}
			got := utils.ShouldSkipTestFile(pass, file)
			if got != tt.want {
				t.Errorf("ShouldSkipTestFile() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestShouldSkipGeneratedFile(t *testing.T) {
	tests := []struct {
		name string
		file *ast.File
		want bool
	}{
		{
			name: "regular file",
			file: &ast.File{},
			want: false,
		},
		{
			name: "generated file",
			file: &ast.File{
				Comments: []*ast.CommentGroup{
					{List: []*ast.Comment{{Text: "// Code generated"}}},
				},
			},
			want: true,
		},
	}

	for _, tt := range tests {
		tt := tt // Capture range variable
		t.Run(tt.name, func(t *testing.T) {
			got := utils.ShouldSkipGeneratedFile(tt.file)
			if got != tt.want {
				t.Errorf("ShouldSkipGeneratedFile() = %v, want %v", got, tt.want)
			}
		})
	}
}
